-- Generated by HyprMod

-- Settings
hl.config({
    input = {
        follow_mouse = 1,
        numlock_by_default = true,
    },
})

-- Monitors
hl.monitor({
    output = "DP-3",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "0x240",
    scale = 1,
    cm = "srgb",
})

-- Window rules
hl.window_rule({
    name = "Floating window",
    match = {
        class = "^(steam)$",
    },
    float = true,
    center = true,
    size = { "monitor_w*0.60", "monitor_h*0.60" },
})
